2024-04-12 12:16:24,113 INFO    MainThread:22016 [internal.py:wandb_internal():63] W&B internal server running at pid: 22016
2024-04-12 12:16:24,115 INFO    WriterThread:22016 [datastore.py:open_for_write():76] open: wandb/run-20240412_121623-l6ffh7bj/run-l6ffh7bj.wandb
2024-04-12 12:16:24,115 DEBUG   HandlerThread:22016 [handler.py:handle_request():55] handle_request: check_version
2024-04-12 12:16:24,116 DEBUG   SenderThread:22016 [sender.py:send():90] send: header
2024-04-12 12:16:24,116 DEBUG   SenderThread:22016 [sender.py:send():90] send: request
2024-04-12 12:16:24,116 DEBUG   SenderThread:22016 [sender.py:send_request():99] send_request: check_version
2024-04-12 12:16:24,120 DEBUG   Thread-4  :22016 [connectionpool.py:_new_conn():1023] Starting new HTTPS connection (1): pypi.org:443
2024-04-12 12:16:24,145 DEBUG   Thread-4  :22016 [connectionpool.py:_make_request():483] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 82344
2024-04-12 12:16:24,161 DEBUG   SenderThread:22016 [sender.py:send():90] send: run
2024-04-12 12:16:24,169 DEBUG   SenderThread:22016 [cmd.py:execute():815] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/workspace/UDA_Bearing_Fault_Diagnosis, universal_newlines=False, shell=None, istream=<valid stream>)
2024-04-12 12:16:24,176 DEBUG   SenderThread:22016 [connectionpool.py:_new_conn():1023] Starting new HTTPS connection (1): api.wandb.ai:443
