04-14 14:19:32 imba: False
04-14 14:19:32 model_name: DANN
04-14 14:19:32 Domain: SEU
04-14 14:19:32 source: SEU_1
04-14 14:19:32 target: SEU_0
04-14 14:19:32 data_dir: /home/workspace/UDA_Bearing_Fault_Diagnosis/datasets
04-14 14:19:32 train_mode: single_source
04-14 14:19:32 cuda_device: 0
04-14 14:19:32 save_dir: ./ckpt/DANN/single_source
04-14 14:19:32 max_epoch: 100
04-14 14:19:32 batch_size: 64
04-14 14:19:32 num_workers: 0
04-14 14:19:32 signal_size: 2048
04-14 14:19:32 random_state: 75
04-14 14:19:32 normlizetype: mean-std
04-14 14:19:32 opt: sgd
04-14 14:19:32 lr: 0.001
04-14 14:19:32 momentum: 0.9
04-14 14:19:32 betas: (0.9, 0.999)
04-14 14:19:32 weight_decay: 0.0005
04-14 14:19:32 lr_scheduler: stepLR
04-14 14:19:32 gamma: 0.2
04-14 14:19:32 steps: 10
04-14 14:19:32 tradeoff: ['exp', 'exp', 'exp']
04-14 14:19:32 dropout: 0.0
04-14 14:19:32 save: False
04-14 14:19:32 load_path: 
04-14 14:19:32 tsne: False
04-14 14:19:32 save_path: ./ckpt/DANN/single_source/[SEU_1]To[SEU_0]_0414-141932
04-14 14:19:32 Detect 10 classes: ['1normal_bearing', '1normal_gear', 'ball', 'chipped', 'comb', 'inner', 'miss', 'outer', 'root', 'surface']
04-14 14:19:32 using 1 / 1 gpus
Loading source: SEU, Condition: 1
Traceback (most recent call last):
  File "train.py", line 89, in <module>
    trainer = importlib.import_module(f"models.{args.model_name}").Trainset(args)
  File "/home/workspace/UDA_Bearing_Fault_Diagnosis/models/DANN.py", line 36, in __init__
    self._init_data()
  File "/home/workspace/UDA_Bearing_Fault_Diagnosis/train_utils.py", line 103, in _init_data
    self.datasets[source] = Dataset(data_root, src, args.faults, args.signal_size, args.normlizetype, condition=condition
  File "/home/workspace/UDA_Bearing_Fault_Diagnosis/data_loader/source_load.py", line 58, in __init__
    self.train_data, self.train_labels = get_files(root=data_dir, dataset=dataset, faults=faults, signal_size=signal_size, condition=condition)
  File "/home/workspace/UDA_Bearing_Fault_Diagnosis/data_loader/source_load.py", line 17, in get_files
    for item in os.listdir(data_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/home/workspace/UDA_Bearing_Fault_Diagnosis/datasets/SEU/condition_1/1normal_gear'
