2024-04-14 09:32:30,122 INFO    MainThread:14335 [internal.py:wandb_internal():63] W&B internal server running at pid: 14335
2024-04-14 09:32:30,124 INFO    WriterThread:14335 [datastore.py:open_for_write():76] open: wandb/run-20240414_093229-z6j50uge/run-z6j50uge.wandb
2024-04-14 09:32:30,124 DEBUG   HandlerThread:14335 [handler.py:handle_request():55] handle_request: check_version
2024-04-14 09:32:30,125 DEBUG   SenderThread:14335 [sender.py:send():90] send: header
2024-04-14 09:32:30,126 DEBUG   SenderThread:14335 [sender.py:send():90] send: request
2024-04-14 09:32:30,126 DEBUG   SenderThread:14335 [sender.py:send_request():99] send_request: check_version
2024-04-14 09:32:30,129 DEBUG   Thread-4  :14335 [connectionpool.py:_new_conn():1023] Starting new HTTPS connection (1): pypi.org:443
2024-04-14 09:32:30,150 DEBUG   Thread-4  :14335 [connectionpool.py:_make_request():483] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 82344
2024-04-14 09:32:30,166 DEBUG   SenderThread:14335 [sender.py:send():90] send: run
2024-04-14 09:32:30,175 DEBUG   SenderThread:14335 [cmd.py:execute():815] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/workspace/UDA_Bearing_Fault_Diagnosis, universal_newlines=False, shell=None, istream=<valid stream>)
2024-04-14 09:32:30,182 DEBUG   SenderThread:14335 [connectionpool.py:_new_conn():1023] Starting new HTTPS connection (1): api.wandb.ai:443
2024-04-14 09:32:30,429 DEBUG   SenderThread:14335 [connectionpool.py:_make_request():483] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2024-04-14 09:32:30,435 INFO    SenderThread:14335 [dir_watcher.py:__init__():164] watching files in: wandb/run-20240414_093229-z6j50uge/files
2024-04-14 09:32:30,435 INFO    SenderThread:14335 [sender.py:_start_run_threads():490] run started: z6j50uge with start time 1713087149
2024-04-14 09:32:30,457 DEBUG   HandlerThread:14335 [handler.py:handle_request():55] handle_request: run_start
2024-04-14 09:32:30,457 DEBUG   SenderThread:14335 [sender.py:send():90] send: summary
2024-04-14 09:32:30,457 INFO    SenderThread:14335 [sender.py:_save_file():568] saving file wandb-summary.json with policy end
2024-04-14 09:32:30,470 DEBUG   HandlerThread:14335 [cmd.py:execute():815] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/workspace/UDA_Bearing_Fault_Diagnosis, universal_newlines=False, shell=None, istream=<valid stream>)
2024-04-14 09:32:30,475 DEBUG   HandlerThread:14335 [cmd.py:execute():815] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/home/workspace/UDA_Bearing_Fault_Diagnosis, universal_newlines=False, shell=None, istream=None)
2024-04-14 09:32:30,506 DEBUG   SenderThread:14335 [sender.py:send():90] send: files
2024-04-14 09:32:30,507 INFO    SenderThread:14335 [sender.py:_save_file():568] saving file wandb-metadata.json with policy now
2024-04-14 09:32:30,511 DEBUG   HandlerThread:14335 [handler.py:handle_request():55] handle_request: status
2024-04-14 09:32:30,512 DEBUG   SenderThread:14335 [sender.py:send():90] send: request
2024-04-14 09:32:30,512 DEBUG   Thread-11 :14335 [connectionpool.py:_new_conn():1023] Starting new HTTPS connection (1): api.wandb.ai:443
2024-04-14 09:32:30,512 DEBUG   SenderThread:14335 [sender.py:send_request():99] send_request: status
2024-04-14 09:32:30,515 DEBUG   SenderThread:14335 [connectionpool.py:_new_conn():1023] Starting new HTTPS connection (1): api.wandb.ai:443
2024-04-14 09:32:30,733 DEBUG   SenderThread:14335 [connectionpool.py:_make_request():483] https://api.wandb.ai:443 "POST /graphql HTTP/1.1" 200 None
2024-04-14 09:32:30,734 DEBUG   SenderThread:14335 [sender.py:send():90] send: config
2024-04-14 09:32:30,738 DEBUG   SenderThread:14335 [connectionpool.py:_new_conn():1023] Starting new HTTPS connection (1): api.wandb.ai:443
